# ==========================================
# CrocoCamp Configuration for Tutorial 1
# ==========================================
# This configuration file contains paths and settings for Tutorial 1,
# which demonstrates model-observation comparison using MOM6 and World Ocean Database.
#
# See config_template.yaml for more info about each field.
# 
# NOTE: Paths below are pre-configured for NCAR HPC systems (Casper/Derecho).
# If running elsewhere, you will need to adjust these paths to your local setup.

####### INPUT FILES #######
# Directory containing model .nc files to process
model_files_folder: /glade/campaign/cgd/oce/projects/CROCODILE/workshops/2025/CrocoCamp/tutorial_1/in_mom6/

# Model configuration files (must be .nc files)
template_file: /glade/campaign/cgd/oce/projects/CROCODILE/workshops/2025/CrocoCamp/tutorial_1/in_mom6/NWA12_demo_01.nc
static_file: /glade/campaign/cgd/oce/projects/CROCODILE/workshops/2025/CrocoCamp/tutorial_1/in_mom6_ref/NWA12_demo_static.nc
ocean_geometry:  /glade/campaign/cgd/oce/projects/CROCODILE/workshops/2025/CrocoCamp/tutorial_1/in_mom6_ref/NWA12_demo_ocean_geometry.nc

# Directory containing observation files
obs_seq_in_folder: /glade/campaign/cgd/oce/projects/CROCODILE/workshops/2025/CrocoCamp/tutorial_1/in_CrocoLake/

####### OUTPUT FILES #######
# Output directories for processed files (will be created if it doesn't exist)
output_folder: $WORK/crocodile_2025/CrocoCamp/output/tutorial_1/out_obs_seq_in/
input_nml_bck: $WORK/crocodile_2025/CrocoCamp/output/tutorial_1/input_bckp/
trimmed_obs_folder: $WORK/crocodile_2025/CrocoCamp/output/tutorial_1/out_trimmed_obs_seq_in/
parquet_folder: $WORK/crocodile_2025/CrocoCamp/output/tutorial_1/out_parquet/
tmp_folder: $WORK/crocodile_2025/CrocoCamp/output/tutorial_1/tmp/

####### DART #######
# Path to DART's perfect model obs executable
#perfect_model_obs_dir: /glade/u/home/emilanese/work/DART-Casper/models/MOM6/work  #CASPER
perfect_model_obs_dir: /glade/u/home/emilanese/work/DART-Derecho/models/MOM6/work  #DERECHO

# Observation types to interpolate to (can include ALL_<FIELD> entries)
use_these_obs:
   - ALL_TEMPERATURE           # Includes ALL temperature types
   - ALL_SALINITY              # Includes ALL temperature types
#   - ARGO_TEMPERATURE          # Include measurements marked as Argo float temperature
#   - ARGO_SALINITY            # Include measurements marked as Argo float salinity

# Time window for matching observations to model output
time_window:
  days: 999      # Primary time window in days
  hours: 0     # Additional hours
  minutes: 0   # Additional minutes
  seconds: 0   # Additional seconds
  weeks: 0     # Additional weeks
  months: 0    # Additional months (30 days/month)
  years: 0     # Additional years (365 days/year)

# MOM6 variable naming and type
model_state_variables:
  so: QTY_SALINITY
  thetao: QTY_POTENTIAL_TEMPERATURE

layer_name: zl
