# ==========================================
# CrocoCamp Configuration for ROMS test
# ==========================================

# Ocean model used to generate files (MOM6 or ROMS_rutgers)
ocean_model: ROMS_rutgers

####### INPUT FILES #######
# Directory containing model .nc files to process
model_files_folder: $CROCOCAMP_PATH/roms_tests/input/test_2/in_roms/

# Model configuration files (must be .nc files)
roms_filename: $CROCOCAMP_PATH/roms_tests/input/test_2/in_roms/roms_avg_0052.nc

# Directory containing observation files
obs_seq_in_folder: $CROCOCAMP_PATH/roms_tests/input/test_2/in_CrocoLake/

####### OUTPUT FILES #######
# Output directories for processed files (will be created if it doesn't exist)
output_folder: $CROCOCAMP_PATH/roms_tests/output/test_2/out_obs_seq_in/
input_nml_bck: $CROCOCAMP_PATH/roms_tests/output/test_2/input_bckp/
trimmed_obs_folder: $CROCOCAMP_PATH/roms_testsoutput/test_2/out_trimmed_obs_seq_in/
parquet_folder: $CROCOCAMP_PATH/roms_tests/output/test_2/out_parquet/
tmp_folder: $CROCOCAMP_PATH/roms_tests/output/test_2/tmp/

####### DART #######
# Path to DART's perfect model obs executable
perfect_model_obs_dir: $DART_ROOT_PATH/models/ROMS_rutgers/work  #CASPER

# Observation types to interpolate to (can include ALL_<FIELD> entries)
use_these_obs:
   - ALL_TEMPERATURE           # Includes ALL temperature types
   - ALL_SALINITY              # Includes ALL temperature types
#   - ARGO_TEMPERATURE          # Include measurements marked as Argo float temperature
#   - ARGO_SALINITY            # Include measurements marked as Argo float salinity

# Time window for matching observations to model output
time_window:
  days: 999      # Primary time window in days
  hours: 0     # Additional hours
  minutes: 0   # Additional minutes
  seconds: 0   # Additional seconds
  weeks: 0     # Additional weeks
  months: 0    # Additional months (30 days/month)
  years: 0     # Additional years (365 days/year)

# ROMS Rutgers variable naming and type
variables:
  salt: QTY_SALINITY
  temp: QTY_POTENTIAL_TEMPERATURE
  zeta: QTY_SEA_SURFACE_HEIGHT
